services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brain-app
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/brain?schema=public
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  pgdata:
